#!/bin/sh

BRANCH_NAME=$(git branch --show-current)
PATTERN="^(feat|bugfix|hotfix)/[A-Za-z]+-[0-9]+-.+$"

if ! [[ $BRANCH_NAME =~ $PATTERN ]]; then
    echo "브랜치 이름이 규칙에 맞지 않습니다."
    echo "PATTERN: ^(feat|bugfix|hotfix)/[A-Za-z]+-[0-9]+-.+$"
    exit 1
fi
